name = "MatterPower"
uuid = "743831d1-0e6a-4e86-a0c4-1a098a68aca3"
version = "0.5.1"
authors = ["Eiichiro Komatsu <eiichirokomatsu@me.com>"]

[deps]
DoubleExponentialFormulas = "eb426421-6452-4132-80ef-4b100a757ac5"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
julia = "1"
DoubleExponentialFormulas = "0.1"
OrdinaryDiffEqTsit5 = "1.5.0"
Roots = "2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
